name: Build Spilo

on:
  push:
    branches:    
      - production
      - development

jobs:
  push_spilo:
    name: Push Spilo
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      # Allows pushing to the GitHub Container Registry
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3


    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Depot
      uses: depot/setup-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push postgres
      uses: depot/bake-action@v1
      with:
        project: nkjck4c1mb
        push: true
        load: true