name: Build Spilo

on:
  workflow_call:
    inputs:
      production:
        required: true
        type: boolean
        default: false
      spilo_repo:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      production:
        required: true
        type: boolean
        default: false
      spilo_repo:
        required: true
        type: string
        default: alfredcapital/splio

jobs:
  push_spilo:
    name: Push Spilo
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      packages: 'write'
      id-token: write
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v3


    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push
      uses: docker/bake-action@v3
      with:
        push: true
